# Generated by Django 5.0.7 on 2024-11-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum number of people the room can accommodate')),
                ('has_projector', models.BooleanField(default=False)),
                ('has_video_conferencing', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('has_sound_system', models.BooleanField(default=False)),
                ('internet_speed_mbps', models.PositiveIntegerField(blank=True, help_text='Internet speed in Mbps', null=True)),
                ('room_layout', models.CharField(choices=[('round_table', 'Round Table'), ('conference', 'Conference Table'), ('informal', 'Informal Seating')], default='conference', max_length=50)),
                ('temperature_control', models.BooleanField(default=True)),
                ('lighting_control', models.BooleanField(default=True)),
                ('has_refreshments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('start_time', models.TimeField()),
                ('Duration', models.DurationField(help_text='Duration of booking in Hrs')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meeting.rooms')),
            ],
            options={
                'ordering': ['Date'],
                'unique_together': {('room', 'Date', 'start_time')},
            },
        ),
    ]
